version: '3.8'
services:
  postgres:
    container_name: vardiya-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: vardiya
      POSTGRES_PASSWORD: vardiya123
      POSTGRES_DB: vardiya_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: vardiya-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vardiya.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: